run-id = "retailer_region-bagging-ce-on-tf-0p1-le-10-eta-0p1-md-8-ss-1p0"
strategy = "bagging"
partitioner = "retailer_region"
centralised-eval = true
test-fraction = 0.1
local-epochs = 10

[params]
eta = 0.1
max_depth = 8
subsample = 1.0
