run-id = "retailer_region-cycling-ce-off-tf-0p1-le-5-eta-0p1-md-6-ss-0p6"
strategy = "cycling"
partitioner = "retailer_region"
centralised-eval = false
test-fraction = 0.1
local-epochs = 5

[params]
eta = 0.1
max_depth = 6
subsample = 0.6
