run-id = "retailer_region-bagging-ce-off-tf-0p1-le-10-eta-0p05-md-6-ss-1p0"
strategy = "bagging"
partitioner = "retailer_region"
centralised-eval = false
test-fraction = 0.1
local-epochs = 10

[params]
eta = 0.05
max_depth = 6
subsample = 1.0
