run-id = "retailer_region-cycling-ce-on-tf-0p1-le-5-eta-0p05-md-4-ss-0p8"
strategy = "cycling"
partitioner = "retailer_region"
centralised-eval = true
test-fraction = 0.1
local-epochs = 5

[params]
eta = 0.05
max_depth = 4
subsample = 0.8
