run-id = "retailer_region-cycling-ce-off-tf-0p1-le-10-eta-0p05-md-8-ss-1p0"
strategy = "cycling"
partitioner = "retailer_region"
centralised-eval = false
test-fraction = 0.1
local-epochs = 10

[params]
eta = 0.05
max_depth = 8
subsample = 1.0
