run-id = "retailer_region-bagging-ce-on-tf-0p2-le-10-eta-0p05-md-8-ss-0p8"
strategy = "bagging"
partitioner = "retailer_region"
centralised-eval = true
test-fraction = 0.2
local-epochs = 10

[params]
eta = 0.05
max_depth = 8
subsample = 0.8
