run-id = "retailer_region-bagging-ce-on-tf-0p1-le-5-eta-0p1-md-6-ss-0p8"
strategy = "bagging"
partitioner = "retailer_region"
centralised-eval = true
test-fraction = 0.1
local-epochs = 5

[params]
eta = 0.1
max_depth = 6
subsample = 0.8
