run-id = "retailer_region-cycling-ce-off-tf-0p2-le-10-eta-0p05-md-4-ss-0p8"
strategy = "cycling"
partitioner = "retailer_region"
centralised-eval = false
test-fraction = 0.2
local-epochs = 10

[params]
eta = 0.05
max_depth = 4
subsample = 0.8
