run-id = "retailer_region-bagging-ce-on-tf-0p3-le-5-eta-0p1-md-4-ss-0p6"
strategy = "bagging"
partitioner = "retailer_region"
centralised-eval = true
test-fraction = 0.3
local-epochs = 5

[params]
eta = 0.1
max_depth = 4
subsample = 0.6
