run-id = "retailer_region-cycling-ce-off-tf-0p1-le-1-eta-0p05-md-8-ss-0p8"
strategy = "cycling"
partitioner = "retailer_region"
centralised-eval = false
test-fraction = 0.1
local-epochs = 1

[params]
eta = 0.05
max_depth = 8
subsample = 0.8
